// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-1y1jxLJ2W9yMPGsI95Ul_f-4Eujc-0',
    appId: '1:120932562606:web:b891a2dffa9e51206f5f3f',
    messagingSenderId: '120932562606',
    projectId: 'drivesync-8af1b',
    authDomain: 'drivesync-8af1b.firebaseapp.com',
    storageBucket: 'drivesync-8af1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8W2G0xBrmlS8oEwa3RnEJBy8ECYwwo4',
    appId: '1:120932562606:android:134ca6c6ae667da46f5f3f',
    messagingSenderId: '120932562606',
    projectId: 'drivesync-8af1b',
    storageBucket: 'drivesync-8af1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1US9lyMZvhxPheYRgky9Bd_KjVpzbco',
    appId: '1:120932562606:ios:be494e3a7150554d6f5f3f',
    messagingSenderId: '120932562606',
    projectId: 'drivesync-8af1b',
    storageBucket: 'drivesync-8af1b.appspot.com',
    iosBundleId: 'com.example.carRent',
  );
}
